[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mmif-storage-api"
version = "0.1.0"
description = "Tool to manage MMIF files."
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Flask",
    "Framework :: Pytest",
    "Framework :: FastAPI",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14"]
dependencies = [
    "mmif-storage==0.2.0",
	"python-dotenv==1.*",
	"fastapi[standard]==0.141.*",
	"flask==3.1.*",
	"gunicorn==26.*"]

[project.optional-dependencies]
dev = ["pytest==9.*"]

[project.scripts]
start_api = "mmif_storage_api:start_api"
start_www = "mmif_storage_api:start_www"

[project.urls]
homepage = "https://clams.ai"
source = "https://github.com/clamsproject/mmif-storage-api"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["./src"]

[tool.setuptools.package-data]
mmif_storage_api = ["templates/*.html", "static/js/*.js", "static/css/*.css"]

[tool.pytest]
testpaths = ["tests"]
pythonpath = ["src"]

